#!/bin/sh
export ETH32_DIR="/home/$USER/Desktop/salvation_src"
export ETH32_ET="/media/New_Volume/game_files/enemy_territory_wolfenstein/55"
export LD_PRELOAD="$ETH32_DIR/libeth32nix.so"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
cd $ETH32_ET

exec ./et.x86 +set fs_game etpub "$@"
unset LD_PRELOAD
