#!/bin/sh
export ETH32_DIR="/home/$USER/Desktop/salvation_src"
export ETH32_ET="/home/$USER/et-sdl-sound"
export LD_PRELOAD="$ETH32_DIR/libeth32nix.so"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:.
cd $ETH32_ET

exec ./et-sdl-sound "$@"
unset LD_PRELOAD
